Restaurants/Controllers/CartController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurants.Domain.Services;

namespace Restaurants.Controllers
{
    [Authorize(Roles = "user")]
    public class CartController : Controller
    {
        private readonly ICartService _cartService;

        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }

        // GET: Cart
        public ActionResult Index()
        {
            var result = _cartService.CartsIncludeDish();
            return View(result);
        }

        // GET: Cart/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cart/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cart/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int dishId, int restaurantId)
        {
            var result = await _cartService.AddToCardAsync(dishId, restaurantId);
            if (!result.IsSuccess)
                return BadRequest(result.Errors);
            return RedirectToAction("Index", new { id = restaurantId });
        }

        // GET: Cart/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cart/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //GET: Cart/Delete/5
        //public async Task<IActionResult> Delete(int dishId, int restaurantId)
        //{
        //    var result = await _cartService.RemoveFromCardAsync(dishId, restaurantId);
        //    if (!result.IsSuccess)
        //        return BadRequest(result.Errors);
        //    return RedirectToAction(nameof(Index));
        //}

        // POST: Cart/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int dishId, int restaurantId)
        {
            var result = await _cartService.RemoveFromCardAsync(dishId, restaurantId);
            if (!result.IsSuccess)
                return BadRequest(result.Errors);
            return RedirectToAction(nameof(Index));
        }
    }
}

Restaurants/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurants.Domain.Dtos;
using Restaurants.Domain.Services;

namespace Restaurants.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }
        [Authorize(Roles = "user")]
        public ActionResult Create(int id)
        {
            CommentModel model = new CommentModel {RestuarantId = id};
            return View(model);
        }

        // POST: Comment/Create
        [Authorize(Roles = "user")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CommentModel model)
        {
            var result = await _commentService.AddComment(model);
            if (!result.IsSuccess)
                return BadRequest(result.Errors);
            return RedirectToAction("Details", "Restaurant", new { id = model.RestuarantId });
        }
    }
}

Restaurants/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Restaurants.Domain.Dtos;
using Restaurants.Domain.Services;

namespace Restaurants.Controllers
{

    public class RatingController : Controller
    {
        private readonly IRatingService _ratingService;

        public RatingController(IRatingService ratingService)
        {
            _ratingService = ratingService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "user")]
        public async Task<IActionResult> Create(int id, int rating)
        {
            RatingModel model = new RatingModel(){RestaurantId = id, Value = rating};
            var result = await _ratingService.AddRating(model);
            if (!result.IsSuccess)
                return BadRequest(result.Errors);
            return RedirectToAction("Details", "Restaurant", new {id = model.RestaurantId});
        }
    }
}

Restaurants/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurants.Domain.Dtos;
using Restaurants.Domain.Services;
using RestaurantsCore.Models;
using RestaurantsCore.UnitOfWork;

namespace Restaurants.Controllers
{
    
    public class RestaurantController : Controller
    {
        private readonly IRestaurantService _restaurantService;

        public RestaurantController(IRestaurantService restaurantService)
        {
            _restaurantService = restaurantService;
        }
        // GET: Restaurant
        public ActionResult Index()
        {
            List<RestaurantModel> restaurants = _restaurantService.GetAllRestaurants().ToList();
            return View(restaurants);
        }

        // GET: Restaurant/Details/5
        public ActionResult Details(int id)
        {
            var result = _restaurantService.RestaurantDetails(id);
            
            return View(result);
        }

        // GET: Restaurant/Create
        [Authorize(Roles = "administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurant/Create
        [Authorize(Roles = "administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RestaurantModel model)
        {
            var result = await _restaurantService.CreateRestaurant(model);
            if (!result.IsSuccess)
                return BadRequest(result.Errors);
            return RedirectToAction(nameof(Index));
        }

        // GET: Restaurant/Edit/5
        [Authorize(Roles = "administrator")]
        public ActionResult Edit(int id)
        {
            var res = _restaurantService.GetModel(id);
            return View(res);
        }

        // POST: Restaurant/Edit/5
        [Authorize(Roles = "administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RestaurantModel model)
        {
            var result = await _restaurantService.EditRestaurant(model);
            if (!result.IsSuccess)
                return BadRequest(result.Errors);

            return RedirectToAction(nameof(Index));
        }

        // GET: Restaurant/Delete/5
        [Authorize(Roles = "administrator")]
        public ActionResult Delete(int id)
        {
            RestaurantModel model = _restaurantService.GetModel(id);
            return View(model);
        }

        // POST: Restaurant/Delete/5
        [Authorize(Roles = "administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(RestaurantModel model)
        {
            var result = await _restaurantService.DeleteRestaurant(model);
            if (!result.IsSuccess)
                return BadRequest(result.Errors);
            return RedirectToAction(nameof(Index));
        }
    }
}

Restaurants/Views/Restaurant/Create.cshtml
@model Restaurants.Domain.Dtos.RestaurantModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<input class="form-control" type="file" name="DishImage" />*@
                <label asp-for="Path" class="control-label">Фото</label>
                <input asp-for="Path" type="file" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Restaurants/Views/Restaurant/Delete.cshtml
@model Restaurants.Domain.Dtos.RestaurantModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RestaurantModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <input asp-for="Id" type="hidden" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Restaurants/Views/Restaurant/Details.cshtml
@model Restaurants.Domain.Dtos.RestaurantModel

@{
    ViewData["Title"] = "Details";
}

<h1>Кафе @Model.Name</h1>


<h5>Рейтинг @Model.Rating</h5>
@if (User.IsInRole("user"))
{
    <div>
        <p>
            <form asp-controller="Rating" asp-action="Create" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <input asp-for="Id" type="hidden" />
                <div class="form-group">
                    @for (int i = 1; i < 6; i++)
                    {
                        <input type="radio" name="rating" value="@i" />
                    }
                </div>
                <button type="submit" class="btn btn-primary">Изменить рейтинг</button>
            </form>
        </p>
    </div>
}

<div>
    <hr />
    <h3>В нашем кафе @Model.Description</h3>
</div>
<div>
    <span>Список блюд кафе "@Model.Name"</span>
    <br />
    <table class="table">
        <thead>
        <tr>
            <tr>
                <th>
                    №
                </th>
                <th>
                    Название
                </th>
                <th>
                    Описание
                </th>
                <th>
                    Цена
                </th>
                <th></th>
            </tr>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Dishes)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @if (User.IsInRole("user"))
                    {
                        <form asp-controller="Cart" asp-action="Create">
                            <input name="dishId" type="hidden" value="@item.Id" class="form-control" />
                            <input name="restaurantId" type="hidden" value="@Model.Id" class="form-control" />
                            <div class="form-group">
                                <input type="submit" value="Добавить в корзину" class="btn btn-default" />
                            </div>
                        </form>
                    }

                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<br/>
<br/>
<br/>
<br/>
<hr />
<div>
    <p><b>Список комментариев</b></p>
</div>
<hr />
@foreach (var item in Model.Comments)
{
    <span><b>@Html.DisplayFor(modelItem => item.Title)</b></span><br />
    <span><b>@Html.DisplayFor(modelItem => item.UserName)</b></span><br />
    <div>@Html.DisplayFor(modelItem => item.Message)</div>
    <hr />
}
@if (User.IsInRole("user"))
{
    <a class="btn btn-sm btn-primary" asp-controller="Comment" asp-action="Create" asp-route-id="@Model.Id">Добавить комментарий</a>
}

Restaurants/Views/Restaurant/Edit.cshtml
@model Restaurants.Domain.Dtos.RestaurantModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RestaurantModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label">Фото</label>
                <input asp-for="Path" type="file" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Restaurants/Views/Restaurant/Index.cshtml
@model IEnumerable<Restaurants.Domain.Dtos.RestaurantModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Рестораны</h1>
@if (User.IsInRole("administrator"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<table class="table" enctype="multipart/form-data">
    <thead>
        <tr>
            <tr>
                <th>
                    №
                </th>
                <th>
                    Название
                </th>
                <th>
                    Фото
                </th>
                <th>
                    Описание
                </th>
                <th></th>
            </tr>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>        
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <img src="@item.ImagePath" width="600" height="400">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @if (User.IsInRole("administrator"))
                {
                    @Html.ActionLink("Edit", "Edit", new {id = item.Id}) 
                    @Html.ActionLink("Delete", "Delete", new {id = item.Id}) 
                }
                @Html.ActionLink("Details", "Details", new { id = item.Id })

            </td>
        </tr>
}
    </tbody>
</table>